[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "linker=flip-link",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=--nmagic",
]
runner = "probe-rs run --chip STM32H743VITx --catch-hardfault --always-print-stacktrace --log-format '{L} {m:white} {s}'"

[env]
DEFMT_LOG = "info"
