//! Core types for the parameter system.
//!
//! A parameter is addressed by a stable `u16` id (its flash storage key) and carries a raw `u32`
//! payload. Higher layers map ids to MAVLink names.

#![no_std]
#![allow(
    clippy::indexing_slicing,
    reason = "slot indices are bounded by each field's declared WIDTH"
)]

use nalgebra::Vector3;
use rapid_dialect::rapid::enums::MavParamType;

/// The wire/storage type of a single parameter slot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParamType {
    F32,
    U32,
}

/// A single parameter value.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ParamValue {
    F32(f32),
    U32(u32),
}

/// A registered and valid parameter's stable id (its flash storage key).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ParamId(u16);

/// Describes one parameter slot: its stable id, full MAVLink name and type.
#[derive(Debug, Clone, Copy)]
pub struct ParamDescriptor {
    pub id: ParamId,
    pub name: &'static str,
    pub ty: ParamType,
}

/// A single struct field that maps onto one or more parameter slots.
///
/// Scalars occupy one slot; composite types (e.g. [`Vector3`]) occupy several consecutive slots.
/// Implemented for the primitive parameter types; the derive macro dispatches through this trait
/// so it never needs to understand the concrete field type.
pub trait ParameterField: Sized {
    /// Number of parameter slots this field occupies.
    const WIDTH: usize;
    /// The type of every slot (all slots of a field share one type).
    const SLOT_TYPE: ParamType;
    /// The scalar the field is built from (used to type the `default` array).
    type Scalar: Copy;

    fn get_slot(&self, index: usize) -> ParamValue;

    /// Returns false if `value` does not match [`Self::SLOT_TYPE`].
    fn set_slot(&mut self, index: usize, value: ParamValue) -> bool;

    /// Build a field value from its per-slot defaults (`slots.len() == WIDTH`).
    fn from_slots(slots: &[Self::Scalar]) -> Self;
}

/// A struct whose fields are parameters (leaf group) or parameter groups (aggregate).
/// Implementations are generated by the `macros` crate.
pub trait ParameterGroup {
    /// Total number of parameter slots in this group.
    const PARAM_COUNT: usize;

    /// The descriptor at a flat slot index, or None if out of range.
    fn descriptor(index: usize) -> Option<ParamDescriptor>
    where
        Self: Sized;

    /// The current value of the parameter with the given id, if present.
    fn get(&self, id: ParamId) -> Option<ParamValue>;

    /// Apply a value to the parameter with the given id. Returns false if the id does not belong to
    /// this group or the value type does not match.
    fn set(&mut self, id: ParamId, value: ParamValue) -> bool;
}

impl ParamType {
    /// Reconstruct a value from its raw u32 storage representation.
    pub fn decode_raw(self, raw: u32) -> ParamValue {
        match self {
            ParamType::F32 => ParamValue::F32(f32::from_bits(raw)),
            ParamType::U32 => ParamValue::U32(raw),
        }
    }

    /// Reconstruct a value from a MAVLink `param_value` field (bytewise encoding, so the raw bits
    /// arrive unchanged and nothing is lost for u32 params).
    pub fn from_mavlink(self, v: f32) -> Option<ParamValue> {
        match self {
            ParamType::F32 if !v.is_finite() => None,
            _ => Some(self.decode_raw(v.to_bits())),
        }
    }
}

impl From<ParamType> for MavParamType {
    fn from(ty: ParamType) -> Self {
        match ty {
            ParamType::F32 => MavParamType::Real32,
            ParamType::U32 => MavParamType::Uint32,
        }
    }
}

impl ParamValue {
    /// The raw u32 stored in flash (f32 bit pattern or the value itself).
    pub fn encode_raw(self) -> u32 {
        match self {
            ParamValue::F32(v) => v.to_bits(),
            ParamValue::U32(v) => v,
        }
    }

    /// The value as it goes into a MAVLink `param_value` field: the same raw u32 as storage uses,
    /// reinterpreted as a float (bytewise encoding).
    pub fn to_mavlink(self) -> f32 {
        f32::from_bits(self.encode_raw())
    }

    pub fn param_type(self) -> ParamType {
        match self {
            ParamValue::F32(_) => ParamType::F32,
            ParamValue::U32(_) => ParamType::U32,
        }
    }
}

impl ParamId {
    pub const fn new(id: u16) -> Self {
        Self(id)
    }

    pub const fn get(self) -> u16 {
        self.0
    }
}

impl ParamDescriptor {
    /// The name as a 16-byte NUL-padded MAVLink `param_id`.
    pub fn mavlink_name(&self) -> [u8; 16] {
        let mut out = [0u8; 16];
        for (o, b) in out.iter_mut().zip(self.name.bytes()) {
            *o = b;
        }
        out
    }
}

impl ParameterField for f32 {
    const WIDTH: usize = 1;
    const SLOT_TYPE: ParamType = ParamType::F32;
    type Scalar = f32;

    fn get_slot(&self, _index: usize) -> ParamValue {
        ParamValue::F32(*self)
    }

    fn set_slot(&mut self, _index: usize, value: ParamValue) -> bool {
        if let ParamValue::F32(v) = value {
            *self = v;
            true
        } else {
            false
        }
    }

    fn from_slots(slots: &[f32]) -> Self {
        slots[0]
    }
}

impl ParameterField for u32 {
    const WIDTH: usize = 1;
    const SLOT_TYPE: ParamType = ParamType::U32;
    type Scalar = u32;

    fn get_slot(&self, _index: usize) -> ParamValue {
        ParamValue::U32(*self)
    }

    fn set_slot(&mut self, _index: usize, value: ParamValue) -> bool {
        if let ParamValue::U32(v) = value {
            *self = v;
            true
        } else {
            false
        }
    }

    fn from_slots(slots: &[u32]) -> Self {
        slots[0]
    }
}

impl ParameterField for Vector3<f32> {
    const WIDTH: usize = 3;
    const SLOT_TYPE: ParamType = ParamType::F32;
    type Scalar = f32;

    fn get_slot(&self, index: usize) -> ParamValue {
        ParamValue::F32(self[index])
    }

    fn set_slot(&mut self, index: usize, value: ParamValue) -> bool {
        if let ParamValue::F32(v) = value {
            self[index] = v;
            true
        } else {
            false
        }
    }

    fn from_slots(slots: &[f32]) -> Self {
        Vector3::new(slots[0], slots[1], slots[2])
    }
}
